### PR TITLE
Support to other platforms

### PR DESCRIPTION
**Pull request by felipebraz**
Hi, I´m a huge fan of your work with MCUFRIEND_kbv. What I want to know if is there any plans to extend it to other platforms such as ESP32?

### CODE REVIEW

**Comment by prenticedavid** [comment]
I have supported the ESP32 for some time.   It is in the current v2.9.8 Release.
And is obviously in the current Beta i.e. master Branch

You appear to be using the L433 branch.  The L433 has never been an Nucleo in the official STM32 core.
I have added most Nuleo-64 boards.   I intend to add most Nucleo-144 boards to the "master" branch.

What do you want?

David.

**Comment by felipebraz** [comment]
Oooohh really?! Great I´ll research about the pinout and test it!!!!

Sorry, I selected the wrong branch. I´m newbie and sometimes I get a little lost. I really like learning new things, but there is a lot of things to learn!! LoL

**Comment by prenticedavid** [comment]
Just say what you want to do.

v2.9.8 Release is installed by the Library Manager.   It supports ESP32.   You have to make a small hardware mod to the TTGO R32 board.

David.

**Comment by felipebraz** [comment]
What I want to do?

Connect my display (MCU Friend 2.8" https://cyaninfinite.com/2-8-tft-lcd-touchscreen-shield/) to my ESP32 and show informations (temperature, charge status,...) and interact with touch (turn on light, activate solenoids,...) in a project (Solar Garden Control: Charge battery using solar power, irrigates garden according sensors reading, lights,...) that I starting to work.

I will research about these mods. Recommends any doc?

Thank you very much!!!! \o/

**Comment by genelkus** [comment]
Hi. I really like your MCUFRIEND_kbv library, lots of examples. You can add support for the Maple mini Board for the ili9341 display.Thanks!

**Comment by prenticedavid** [comment]
The MapleMini does not have Arduino header sockets.
I suggest that you use the BLUEPILL or NUCLEO-F103 wiring e.g. from utility/mcufriend_shield.h

You have posted on "Pull Requests".   It would be more appropriate for "Issues" or the Arduino.cc Displays Forum.

David.

**Pull request closed without merging**
