### PR TITLE
Added cheap 2.4 TFT/Touchscreen SPFD5408 with 0x9340 ID

### PR DESCRIPTION
**Pull request by sandline**
Hello, I've added the support for the cheap 2.4 LCD TFT/Touchscreen (240x320) SPFD5408 with 0x9340 ID
You can found it on ebay (e.g. http://www.ebay.it/itm/371741095114?_trksid=p2057872.m2749.l2649&ssPageName=STRK%3AMEBIDX%3AIT)

### CODE REVIEW

**Comment by prenticedavid** [comment]
If your ILI9340 works 100% with the Manufacturer configuration,   I would add it to the common_9329 block.   i.e. just adjust any flags like INVERT_GS or READ_24BITS as appropriate.

The ILI9340 is very similar to the ILI9341.   You could simply "fall through" to the 0x9341 case.

If your ILI9340 needs different initialisation to the 0x9341 case,  then it is sensible to create a whole new case (as you have done).

The library is getting too big for convenient use on a Uno.   So it is worth being careful with the size.

David.

**Comment by sandline** [comment]
Hello David,

I just updated the library to test it with the display. I didn't considered any performance/space issue (also because I'm actually testing it with Arduino Mega). :)
I think that the 0x9340 can fall inside the common_9329 case so feel free to update just the flags and ignore the pull request.

Have a nice day,
Marco

**Comment by prenticedavid** [comment]
I don't know which flags or what similarities.   You are the owner of the ILI9340.   Every colour, aspect, scroll, direction, should work perfectly.

Please test your code and either explain or post a pull request.

David.

**Comment by sandline** [comment]
Ok, I close the pull request for the moment while I check that everything works.
Thank you!

**Pull request closed without merging**
